<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9d14cfc3-4a02-4502-9951-d405be8cd826</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snackis.Application\Snackis.Application.csproj" />
    <ProjectReference Include="..\Snackis.Infrastructure\Snackis.Infrastructure.csproj" />
  </ItemGroup>

</Project>
